(function(){
  const cfg=window.METALFORTE_CONFIG||{},el=(id)=>document.getElementById(id);let supa,session,history=[];
  const labels={queued:"Na fila",in_progress:"Em execução",success:"Concluído",failure:"Falhou",cancelled:"Cancelado",pending:"Aguardando",running:"Executando",failed:"Falhou",completed:"Concluído"};
  const safe=(v)=>String(v==null?"—":v).replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const statusClass=(s)=>["success","completed"].includes(s)?"success":["in_progress","running"].includes(s)?"running":["failure","failed","cancelled"].includes(s)?"failed":"pending";
  function demo(){return {id:"modo-local",status:"pending",source:"local",environment:"homologacao",scope:"full",requested_by:"Demonstração local",started_at:null,updated_at:new Date().toISOString(),steps:["Disparo solicitado","Autorização e permissões","Preparação do ambiente","Coleta TOTVS / GoodData","Validação da base","Tratamento e normalização","Publicação da base privada","Geração de métricas e agregados","Publicação do resumo","Validação pós-carga","Painel disponível"].map((name)=>({name,status:"pending",message:"Aguardando integração real"})),events:[]};}
  function formatDate(v){return v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";}
  function renderRun(run){
    run=run||demo();el("run-title").textContent=run.id&&run.id!=="modo-local"?"Carga "+run.id:"Nenhuma execução real registrada";el("run-status").textContent=labels[run.status]||run.status||"Sem dados";el("run-status").className="status "+statusClass(run.status);
    el("run-meta").innerHTML=[["Ambiente",run.environment],["Escopo",run.scope],["Solicitante",run.requested_by],["Atualizado",formatDate(run.updated_at)]].map((x)=>'<div class="meta-item"><span>'+safe(x[0])+'</span><strong>'+safe(x[1])+'</strong></div>').join("");
    el("etl-timeline").innerHTML=(run.steps||[]).map((step)=>'<div class="timeline-step '+statusClass(step.status)+'"><h3>'+safe(step.name)+'</h3><p>'+safe(step.message||labels[step.status]||step.status)+' '+(step.at?"· "+safe(formatDate(step.at)):"")+'</p></div>').join("");
  }
  function renderHistory(rows){history=rows||[];el("etl-history").innerHTML=history.length?history.map((run)=>'<article class="history-item"><strong>'+safe(run.id)+'</strong><span class="status '+statusClass(run.status)+'">'+safe(labels[run.status]||run.status)+'</span><span>'+safe(run.environment)+'</span><span>'+safe(run.requested_by)+'</span><span>'+safe(formatDate(run.updated_at))+'</span></article>').join(""):'<section class="card"><p class="muted">Nenhuma execução real registrada. Configure a integração ou aguarde a próxima carga automática.</p></section>';}
  async function refresh(){try{const [latestResult,historyResult]=await Promise.all([window.MetalforteEtlApi.latest(session),window.MetalforteEtlApi.history(session)]);renderRun(latestResult.run);renderHistory(historyResult.runs);el("connection-badge").textContent="Integração ETL conectada";el("connection-badge").className="status success";}catch(e){renderRun(demo());renderHistory([]);el("connection-badge").textContent="Integração ETL não configurada";el("connection-badge").className="status neutral";el("trigger-message").textContent=e.message;}}
  function updateKpis(){const workflow=window.MetalforteWorkflow.getState();const pending=workflow.tasks.filter((t)=>t.status!=="Concluído").length,blocked=workflow.tasks.filter((t)=>t.priority==="Alta"&&t.status==="Backlog").length;el("tower-kpis").innerHTML=[["Demandas abertas",pending],["Prioridades no backlog",blocked],["Últimas cargas",history.length],["Modo de segurança","Ativo"]].map((x)=>'<article class="kpi"><span>'+safe(x[0])+'</span><strong>'+safe(x[1])+'</strong></article>').join("");}
  async function start(){
    window.MetalforteWorkflow.init();document.addEventListener("workflow:updated",updateKpis);document.querySelectorAll(".tab").forEach((button)=>button.onclick=()=>{document.querySelectorAll(".tab,.tab-panel").forEach((x)=>x.classList.remove("active"));button.classList.add("active");el("tab-"+button.dataset.tab).classList.add("active");});
    if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY){el("login-error").textContent="Configure a chave pública do Supabase em config.js.";return;}
    supa=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);session=(await supa.auth.getSession()).data.session;
    async function enter(){el("login").hidden=true;el("tower").hidden=false;el("logout").hidden=false;await refresh();updateKpis();}
    if(session)await enter();
    el("login-form").onsubmit=async(event)=>{event.preventDefault();const result=await supa.auth.signInWithPassword({email:el("email").value,password:el("password").value});if(result.error){el("login-error").textContent="E-mail ou senha inválidos.";return;}session=result.data.session;await enter();};
    el("logout").onclick=async()=>{await supa.auth.signOut();location.reload();};el("refresh-etl").onclick=refresh;el("open-trigger").onclick=()=>{document.querySelector('[data-tab="etl"]').click();el("trigger-reason").focus();};
    el("trigger-form").onsubmit=async(event)=>{event.preventDefault();const button=event.target.querySelector("button");button.disabled=true;el("trigger-message").textContent="Enviando solicitação...";try{const result=await window.MetalforteEtlApi.trigger(session,{environment:el("trigger-environment").value,scope:el("trigger-scope").value,reason:el("trigger-reason").value.trim(),confirmed:el("trigger-confirm").checked});el("trigger-message").textContent="Solicitação "+result.request_id+" aceita. Acompanhando a fila.";event.target.reset();setTimeout(refresh,2500);}catch(e){el("trigger-message").textContent=e.message;}finally{button.disabled=false;}};
    el("export-history").onclick=()=>{const blob=new Blob([JSON.stringify(history,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="metalforte360-etl-history.json";a.click();URL.revokeObjectURL(a.href);};
  }
  start();
})();
